"resource/UI/WorldMap.res"
{
	"WorldMap"
	{
		"ControlName"		"Frame"
		"fieldName"		"WorldMap"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"900"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
		"paintbackground"		"1"
	}
	"ItemInfo" // must be defined before any mission buttons
	{
		"ControlName"		"Panel"
		"fieldName"		"ItemInfo"
		"xpos"		"0"
		"ypos"		"363"
		"wide"		"731"
		"tall"		"127"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"MissionSelect"
	{
		"ControlName"		"Frame"
		"fieldName"		"MissionSelect"
		"xpos"		"0"
		"ypos"		"40"
		"wide"		"860"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
		"paintbackground"		"1"
	}
	"ibczlogo1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibczlogo1"
		"xpos"			"12"
		"ypos"			"0"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_czlogo1"
		"scaleImage"	"0"
	}
	"ibczlogo2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibczlogo2"
		"xpos"			"126"
		"ypos"			"0"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_czlogo2"
		"scaleImage"	"0"
	}
	"ibwmtitle1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibwmtitle1"
		"xpos"			"734"
		"ypos"			"3"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wmtitle1"
		"scaleImage"	"0"
	}
	"ibwmtitle2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibwmtitle2"
		"xpos"			"620"
		"ypos"			"3"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wmtitle2"
		"scaleImage"	"0"
	}
	"ibgrid1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid1"
		"xpos"			"56"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm1"
		"scaleImage"	"0"
	}
	"ibgrid2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid2"
		"xpos"			"170"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm2"
		"scaleImage"	"0"
	}
	"ibgrid3"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid3"
		"xpos"			"283"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm3"
		"scaleImage"	"0"
	}
	"ibgrid4"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid4"
		"xpos"			"396"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm4"
		"scaleImage"	"0"
	}
	"ibgrid5"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid5"
		"xpos"			"510"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm5"
		"scaleImage"	"0"
	}
	"ibgrid6"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid6"
		"xpos"			"623"
		"ypos"			"40"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm6"
		"scaleImage"	"0"
	}
	"ibgrid7"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid7"
		"xpos"			"56"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm7"
		"scaleImage"	"0"
	}
	"ibgrid8"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid8"
		"xpos"			"170"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm8"
		"scaleImage"	"0"
	}
	"ibgrid9"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid9"
		"xpos"			"283"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm9"
		"scaleImage"	"0"
	}
	"ibgrid10"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid10"
		"xpos"			"396"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm10"
		"scaleImage"	"0"
	}
	"ibgrid11"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid11"
		"xpos"			"510"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm11"
		"scaleImage"	"0"
	}
	"ibgrid12"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid12"
		"xpos"			"623"
		"ypos"			"154"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm12"
		"scaleImage"	"0"
	}
	"ibgrid14"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid14"
		"xpos"			"170"
		"ypos"			"267"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm14"
		"scaleImage"	"0"
	}
	"ibgrid15"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid15"
		"xpos"			"283"
		"ypos"			"267"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm15"
		"scaleImage"	"0"
	}
	"ibgrid16"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid16"
		"xpos"			"396"
		"ypos"			"267"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm16"
		"scaleImage"	"0"
	}
	"ibgrid17"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid17"
		"xpos"			"510"
		"ypos"			"267"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm17"
		"scaleImage"	"0"
	}
	"ibgrid18"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibgrid18"
		"xpos"			"623"
		"ypos"			"267"
		"wide"			"256"
		"tall"			"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_wm18"
		"scaleImage"	"0"
	}
	"iblegend1"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"iblegend1"
		"xpos"			"9"
		"ypos"			"164"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_legend"
		"scaleImage"	"0"
	}
	"ibmarker"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibmarker"
		"xpos"			"647"
		"ypos"			"142"
		"wide"			"32"
		"tall"			"32"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_marker"
		"scaleImage"	"0"
	}
	"ibTokyo"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ibTokyo"
		"xpos"			"674"
		"ypos"			"59"
		"wide"			"256"
		"tall"			"256"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/ib_tokyo"
		"scaleImage"	"0"
	}
	"TrainingCamp"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"TrainingCamp"
		"xpos"		"139"
		"ypos"		"129"
		"wide"		"146"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#TRAINING_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_train01"
	}
	"LostCause"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"LostCause"
		"xpos"		"625"
		"ypos"		"216"
		"wide"		"76"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#LOSTCAUSE_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_lostcause"
	}
	"Recoil"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Recoil"
		"xpos"		"401"
		"ypos"		"181"
		"wide"		"51"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#RECOIL_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_recoil-intro"
	}
	"SecretWar"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"SecretWar"
		"xpos"		"545"
		"ypos"		"71"
		"wide"		"76"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#SILO_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_silo01"
	}
	"BuildingRecon"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"BuildingRecon"
		"xpos"		"400"
		"ypos"		"86"
		"wide"		"96"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#BRECON_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_brecon01"
	}
	"DrugLab"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"DrugLab"
		"xpos"		"185"
		"ypos"		"216"
		"wide"		"66"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#DRUGLAB_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_druglab1"
	}
	"Motorcade"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Motorcade"
		"xpos"		"380"
		"ypos"		"116"
		"wide"		"111"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#MOTORCADE_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_motor1"
	}
	"ThinIce"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"ThinIce"
		"xpos"		"340"
		"ypos"		"51"
		"wide"		"56"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#THINICE_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_thinice01"
	}
	"DownedPilot"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"DownedPilot"
		"xpos"		"235"
		"ypos"		"301"
		"wide"		"91"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#DOWNED_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_downed1"
	}
	"Turncrank"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Turncrank"
		"xpos"		"95"
		"ypos"		"141"
		"wide"		"101"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#TURNCRANK_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_turncrank"
	}
	"Hankagai"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Hankagai"
		"xpos"		"687"
		"ypos"		"93"
		"wide"		"66"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#HANKAGAI_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_hankagai1"
	}
	"Alamo"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Alamo"
		"xpos"		"375"
		"ypos"		"141"
		"wide"		"56"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#ALAMO_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_alamo"
	}
	"RiseHard"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"RiseHard"
		"xpos"		"340"
		"ypos"		"91"
		"wide"		"66"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#HIGHRISE_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_hr01"
	}

// bonus missions
	"SupremeTruth"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"SupremeTruth"
		"xpos"		"635"
		"ypos"		"151"
		"wide"		"101"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#TRUTH_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_truth1"
	}
	"Run"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Run"
		"xpos"		"749"
		"ypos"		"117"
		"wide"		"66"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#RUN_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_run1"
	}
	"MiamiHeat"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"MiamiHeat"
		"xpos"		"175"
		"ypos"		"166"
		"wide"		"86"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#MIAMI_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_miami1"
	}
	"Fastline"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Fastline"
		"xpos"		"734"
		"ypos"		"105"
		"wide"		"66"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#FASTLINE_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_fastline1"
	}
	"Pipedream"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Pipedream"
		"xpos"		"480"
		"ypos"		"126"
		"wide"		"86"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#PIPEDREAM_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_pipedream1"
	}
	"Sandstorm"
	{
		"ControlName"		"MissionButton"
		"fieldName"		"Sandstorm"
		"xpos"		"450"
		"ypos"		"146"
		"wide"		"81"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#SANDSTORM_TITLE"
		"textAlignment"		"south"
		"dulltext"		"0"
		"brighttext"		"0"
		"map"		"cz_sandstorm"
	}
	"MissionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MissionLabel"
		"xpos"		"139"
		"ypos"		"373"
		"wide"		"90"
		"tall"		"39"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CZERO_Mission"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"MissionLabelFont"
	}
	"Resume"
	{
		"ControlName"		"Button"
		"fieldName"			"Resume"
		"xpos"				"739"
		"ypos"				"426"
		"wide"				"80"
		"tall"				"26"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"0"
		"tabPosition"		"0"
		"labelText"			"#CZERO_Resume"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"resume"
		"Default"			"0"
	}
}
